# Generated by Django 3.1 on 2020-09-28 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('tech_check_payment_accepted', 'tech check payment accepted'), ('tech_check_payment_rejected', 'tech check payment rejected'), ('remove_request_accepted', 'remove request accepted'), ('wait', 'wait'), ('look', 'look'), ('rejected', 'rejected'), ('payment', 'waiting for payment'), ('payment_check', 'waiting for payment check'), ('payment_rejected', 'payment rejected'), ('inspector_check', 'waiting for data check'), ('accepted', 'accepted')], max_length=250)),
                ('watched', models.BooleanField(default=False)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('boat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boat.boat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
