# Generated by Django 3.1.1 on 2020-09-30 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=300, verbose_name='Тип и модель')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('imo', models.CharField(max_length=250, verbose_name='Идентификационный номер (IMO)')),
                ('build_place', models.CharField(max_length=300, verbose_name='Место создания')),
                ('build_year', models.PositiveIntegerField(verbose_name='Год создания')),
                ('material', models.CharField(max_length=200, verbose_name='Материал корпуса')),
                ('length', models.PositiveIntegerField(verbose_name='Длина (м)')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина (м)')),
                ('height_board', models.PositiveIntegerField(verbose_name='Высота борта (м)')),
                ('height_second_board', models.PositiveIntegerField(verbose_name='Высота надводного борта (м)')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (тонн)')),
                ('capacity_load', models.PositiveIntegerField(verbose_name='Грузоподъемность судна (кг)')),
                ('passenger_awn', models.PositiveIntegerField(verbose_name='Пассажировместимость судна (чел.)')),
                ('swimming_place', models.CharField(max_length=300, verbose_name='Район и условия хождения(плавания)')),
                ('engine_type', models.CharField(max_length=300, verbose_name='Тип главного двигателя')),
                ('engine_model', models.CharField(max_length=300, verbose_name='Марка двигателя')),
                ('engine_number', models.CharField(max_length=300, verbose_name='Заводские номера двигателей')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя/ей (кВт/л.с.)')),
                ('sails_amount', models.PositiveIntegerField(verbose_name='Количество парусов')),
                ('sail_area', models.PositiveIntegerField(verbose_name='Площадь парусов (м2)')),
                ('prev_numbers_or_name', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Прежние регистр. No и название судна')),
                ('prev_registration_place', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Место прежней регистрации судна')),
                ('parking_place', models.CharField(max_length=300, verbose_name='Место постоянной стоянки судна')),
                ('passport_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Скан паспорта')),
                ('other_files', models.FileField(blank=True, null=True, upload_to='', verbose_name='Другие файлы')),
                ('status', models.CharField(choices=[('wait', 'wait'), ('look', 'look'), ('rejected', 'rejected'), ('payment', 'waiting for payment'), ('payment_check', 'waiting for payment check'), ('payment_rejected', 'payment rejected'), ('inspector_check', 'waiting for data check'), ('accepted', 'accepted')], default='wait', max_length=100)),
                ('incorrect_fields', models.TextField(default='[]')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
