# Generated by Django 2.1.7 on 2019-02-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190212_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
    ]
