# Generated by Django 2.1.7 on 2019-02-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_inspector',
            field=models.BooleanField(default=False),
        ),
    ]
