# Generated by Django 2.1.7 on 2019-02-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190213_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name_of_organiszation',
            new_name='name_of_organization',
        ),
    ]
