# Generated by Django 2.1.7 on 2019-02-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190214_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
