# Generated by Django 2.1.7 on 2019-02-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_owner_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=250)),
                ('imo', models.CharField(max_length=250)),
                ('build_place', models.CharField(max_length=300)),
                ('build_year', models.IntegerField()),
                ('material', models.CharField(choices=[('wood', 'wood'), ('other', 'other')], max_length=200)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height_board', models.IntegerField()),
                ('height_second_board', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('capacity_load', models.IntegerField()),
                ('passenger_awn', models.IntegerField()),
                ('swimming_place', models.CharField(max_length=300)),
                ('engine_type', models.CharField(max_length=300)),
                ('engine_model', models.CharField(max_length=300)),
                ('engine_power', models.IntegerField()),
                ('sails_amount', models.IntegerField()),
                ('sail_area', models.IntegerField()),
                ('prev_numbers_or_name', models.CharField(max_length=300)),
                ('prev_registration_place', models.CharField(max_length=300)),
                ('parking_place', models.CharField(max_length=300)),
            ],
        ),
    ]
