# Generated by Django 2.1.7 on 2019-02-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190215_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='second_name',
        ),
    ]
