# Generated by Django 2.1.7 on 2019-02-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_owner_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='build_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='capacity_load',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='engine_power',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='height_board',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='height_second_board',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='length',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='passenger_awn',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sail_area',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sails_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='width',
            field=models.PositiveIntegerField(),
        ),
    ]
