# Generated by Django 2.1.7 on 2019-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190215_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('look', 'look'), ('rejected', 'rejected'), ('waiting for payment', 'payment'), ('accepted', 'accepted')], default='wait', max_length=100),
            preserve_default=False,
        ),
    ]
