# Generated by Django 2.1.7 on 2019-02-23 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190219_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
        migrations.AlterModelManagers(
            name='owner',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
        migrations.AlterField(
            model_name='boat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Owner'),
        ),
    ]
