# Generated by Django 2.1.7 on 2019-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190223_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
