# Generated by Django 2.1.7 on 2019-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_notification_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='engine_number',
            field=models.CharField(default='', max_length=300, verbose_name='Заводские номера двигателей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boat',
            name='build_place',
            field=models.CharField(max_length=300, verbose_name='Место постройки'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='build_year',
            field=models.PositiveIntegerField(verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Вместимость (тонн)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='capacity_load',
            field=models.PositiveIntegerField(verbose_name='Грузоподъемность (кг)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='engine_model',
            field=models.CharField(max_length=300, verbose_name='Марка двигателя или подвесного лодочного мотора'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='engine_power',
            field=models.PositiveIntegerField(verbose_name='Мощность двигателя/ей (суммарная) (кВт/л.с.)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='engine_type',
            field=models.CharField(max_length=300, verbose_name='Тип главного двигателя или подвесного лодочного мотора'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='height_board',
            field=models.PositiveIntegerField(verbose_name='Высота борта (м)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='height_second_board',
            field=models.PositiveIntegerField(verbose_name='высота надв. Борта (м)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='imo',
            field=models.CharField(max_length=250, verbose_name='Идентификационный (IMO)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='length',
            field=models.PositiveIntegerField(verbose_name='Длина (м)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='material',
            field=models.CharField(choices=[('wood', 'wood'), ('other', 'other')], max_length=200, verbose_name='Материал корпуса'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='model_type',
            field=models.CharField(max_length=300, verbose_name='Тип и модель'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='parking_place',
            field=models.CharField(max_length=300, verbose_name='Место постоянной стоянки судна'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='passenger_awn',
            field=models.PositiveIntegerField(verbose_name='Пассажировместимость (чел.)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='prev_numbers_or_name',
            field=models.CharField(max_length=300, verbose_name='Прежние регистр. No и название судна (если таковые имелись)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='prev_registration_place',
            field=models.CharField(max_length=300, verbose_name='Место прежней регистрации судна'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sail_area',
            field=models.PositiveIntegerField(verbose_name='Площадь парусов (суммарная) (м2)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sails_amount',
            field=models.PositiveIntegerField(verbose_name='Количество парусов'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='swimming_place',
            field=models.CharField(max_length=300, verbose_name='Район и условия плавания'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Ширина (м)'),
        ),
    ]
