# Generated by Django 2.1.7 on 2019-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190228_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='other_files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='boat',
            name='passport_image',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
