# Generated by Django 2.1.7 on 2019-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190305_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date_of_passport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
