# Generated by Django 2.1.7 on 2019-03-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190305_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
