# Generated by Django 2.1.7 on 2019-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_owner_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='activation_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
