# Generated by Django 2.1.7 on 2019-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20190307_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
