# Generated by Django 2.1.7 on 2019-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_owner_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
