# Generated by Django 2.1.7 on 2019-03-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20190315_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='_status',
            new_name='status',
        ),
    ]
