# Generated by Django 2.1.7 on 2019-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20190316_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=20, null=True, verbose_name='Пол'),
        ),
    ]
