# Generated by Django 2.1.7 on 2019-03-25 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20190316_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCheckRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('первичный', 'first'), ('ежегодный', 'year')], max_length=100)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Boat')),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='activation_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код активации'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_of_passport',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата выдачи и серия паспорта'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=300, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='inn',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='is_inspector',
            field=models.BooleanField(default=False, verbose_name='Является инспектором'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='mail_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name_of_organization',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Номер телефона'),
        ),
    ]
