# Generated by Django 2.1.7 on 2019-03-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20190324_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='incorrect_fields',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('look', 'look'), ('rejected', 'rejected'), ('waiting for payment', 'payment'), ('accepted', 'accepted')], default='wait', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('look', 'look'), ('rejected', 'rejected'), ('waiting for payment', 'payment'), ('accepted', 'accepted')], max_length=250),
        ),
    ]
