# Generated by Django 2.1.7 on 2019-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20190325_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='other_files',
            field=models.FileField(null=True, upload_to='', verbose_name='Другие файлы'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='passport_image',
            field=models.FileField(upload_to='', verbose_name='Скан паспорта'),
        ),
        migrations.AlterField(
            model_name='removerequest',
            name='reason',
            field=models.CharField(choices=[('Изменение владельца или места жительства', 'change'), ('Износ или поломка судна', 'broke'), ('Утеря или порча судового билета', 'ticket')], max_length=300),
        ),
    ]
