# Generated by Django 2.1.7 on 2019-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20190326_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='removerequest',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
