# Generated by Django 2.1.7 on 2019-03-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_removerequest_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removerequest',
            name='reason',
            field=models.CharField(choices=[('change', 'Изменение владельца или места жительства'), ('broke', 'Износ или поломка судна'), ('ticket', 'Утеря или порча судового билета')], max_length=300),
        ),
    ]
