# Generated by Django 2.1.7 on 2019-04-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20190329_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcheckrequest',
            name='check_type',
            field=models.CharField(choices=[('first', 'первичный'), ('year', 'ежегодный')], max_length=100),
        ),
    ]
