# Generated by Django 2.1.7 on 2019-04-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20190401_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('look', 'look'), ('rejected', 'rejected'), ('payment', 'waiting for payment'), ('check', 'waiting for check'), ('accepted', 'accepted')], default='wait', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('look', 'look'), ('rejected', 'rejected'), ('payment', 'waiting for payment'), ('check', 'waiting for check'), ('accepted', 'accepted')], max_length=250),
        ),
    ]
