# Generated by Django 2.1.7 on 2019-04-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_payrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrequest',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='payrequest',
            name='owner',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='user',
            new_name='owner',
        ),
        migrations.DeleteModel(
            name='PayRequest',
        ),
    ]
