# Generated by Django 2.1.7 on 2019-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20190404_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
