# Generated by Django 2.1.7 on 2019-04-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_paymentrequest_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
