# Generated by Django 2.1.7 on 2019-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20190406_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='other_files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Другие файлы'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='passport_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Скан паспорта'),
        ),
    ]
