# Generated by Django 2.1.7 on 2019-04-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20190408_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
