# Generated by Django 2.1.7 on 2019-04-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_fine_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='fine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fine'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Boat'),
        ),
    ]
