# Generated by Django 2.1.7 on 2019-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20190409_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='inspecting',
            field=models.BooleanField(default=True),
        ),
    ]
