# Generated by Django 2.1.7 on 2019-04-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_paymentrequest_inspecting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='inspecting',
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='boat',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='main.Boat'),
            preserve_default=False,
        ),
    ]
