# Generated by Django 2.1.7 on 2019-04-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20190409_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinePaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_scan', models.FileField(upload_to='')),
                ('inspecting', models.BooleanField(default=False)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fine')),
            ],
        ),
    ]
