# Generated by Django 2.1.7 on 2019-04-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_finepaymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='inspecting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finepaymentrequest',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finepaymentrequest',
            name='inspecting',
            field=models.BooleanField(default=True),
        ),
    ]
