# Generated by Django 2.1.7 on 2019-04-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20190409_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcheckrequest',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
