# Generated by Django 2.1.7 on 2019-04-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_techcheckrequest_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcheckrequest',
            name='check_scan',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
