# Generated by Django 2.1.7 on 2019-04-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_techcheckrequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcheckrequest',
            name='inspecting',
            field=models.BooleanField(default=True),
        ),
    ]
