# Generated by Django 2.1.7 on 2019-04-11 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20190410_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='removerequest',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Boat'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('tech_check_payment_accepted', 'tech check payment accepted'), ('tech_check_payment_rejected', 'tech check payment rejected'), ('remove_request_accepted', 'remove request accepted'), ('wait', 'wait'), ('look', 'look'), ('rejected', 'rejected'), ('payment', 'waiting for payment'), ('payment_check', 'waiting for payment check'), ('payment_rejected', 'payment rejected'), ('inspector_check', 'waiting for data check'), ('accepted', 'accepted')], max_length=250),
        ),
    ]
