# Generated by Django 3.1.1 on 2020-09-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20190411_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='father_name',
            field=models.CharField(default='', max_length=250, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boat',
            name='build_place',
            field=models.CharField(max_length=300, verbose_name='Место создания'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='build_year',
            field=models.PositiveIntegerField(verbose_name='Год создания'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='capacity_load',
            field=models.PositiveIntegerField(verbose_name='Грузоподъемность судна (кг)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='height_second_board',
            field=models.PositiveIntegerField(verbose_name='Высота надводного борта (м)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='imo',
            field=models.CharField(max_length=250, verbose_name='Идентификационный номер (IMO)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='passenger_awn',
            field=models.PositiveIntegerField(verbose_name='Пассажировместимость судна (чел.)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='swimming_place',
            field=models.CharField(max_length=300, verbose_name='Район и условия хождения(плавания)'),
        ),
    ]
