# Generated by Django 3.1.1 on 2020-09-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20200925_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='subject',
            field=models.CharField(blank=True, choices=[('Физ. лицо', 'Физ.лицо'), ('Юрид. лицо', 'Юрид. лицо')], max_length=40, null=True, verbose_name='Вид субъекта'),
        ),
    ]
