# Generated by Django 3.1.1 on 2020-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_owner_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='build_year',
            field=models.DateField(verbose_name='Год создания'),
        ),
    ]
