# Generated by Django 3.1.1 on 2020-09-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20200926_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='material',
            field=models.CharField(max_length=200, verbose_name='Материал корпуса'),
        ),
    ]
