# Generated by Django 3.1.1 on 2020-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_auto_20200926_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='build_year',
            field=models.PositiveIntegerField(verbose_name='Год создания'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='material',
            field=models.CharField(choices=[('wood', 'wood'), ('other', 'other')], max_length=200, verbose_name='Материал корпуса'),
        ),
    ]
