# Generated by Django 3.1.1 on 2020-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20200926_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='build_year',
            field=models.PositiveIntegerField(verbose_name='Год создания'),
        ),
    ]
