# Generated by Django 3.1.1 on 2020-09-29 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('payed', models.BooleanField(default=False)),
                ('inspecting', models.BooleanField(default=False)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat.boat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinePaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_scan', models.FileField(upload_to='')),
                ('payed', models.BooleanField(default=False)),
                ('inspecting', models.BooleanField(default=True)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fine.fine')),
            ],
        ),
    ]
